### ISSUE TITLE
Event Subscription not working

### ISSUE THREAD

**Issue by asacchettacali** [Traeger-GmbH/opcuanet-samples#9]
Hello, 
I tried to implement the example illustrated [here](https://www.nuget.org/packages/Opc.UaFx.Advanced) but unfortunately the event pub / sub doesn't seem to work on either my MacOS and Windows:

![Screenshot 2023-04-18 at 15 16 35](https://user-images.githubusercontent.com/14023939/232790039-d495cb1e-676e-4a1a-bdbe-23d89c986c37.png)

Can you help me?
Thank you

**Comment by janbiehl** [comment]
Hey, i had the same issue. I tried to rollback to an older version and this fixed the error for me.

So i am not using the latest 2.30.0. Instead im am using 2.29.0 and the code just works without further changes.

![image](https://user-images.githubusercontent.com/23404664/233552373-8d6d62cf-a378-449e-8e52-3ef0553b8464.png)

**Comment by kpreisser** [comment]
Hi, thanks for creating this issue! Can you try to create an `OpcEventFilter` and pass it to `client.SubscribeEvent()`, like this:

```cs
var eventFilter = OpcFilter.Using(client).FromEvents(OpcEventTypes.Event).Select();
client.SubscribeEvent(OpcObjectTypes.Server, eventFilter, HandleGlobalEvents);
```

There seems to be an issue in the current version of the OPC UA .NET SDK, which causes the event subscription to not work if no `OpcEventFilter` is specified (that defines the event fields that the server sends to the client). We are currently investiaging this issue.

Thanks!

**Comment by asacchettacali** [comment]
Hello,

Thank you for the suggestion, it now works correctly.

Cheers,
Alessio

**Comment by kpreisser** [comment]
Hi,
sorry that it took so long, but we have now fixed the issue that the event subscription doesn't work (since v2.29.0) when no `OpcEventFilter` is specified. The fix will be included in OPC UA .NET SDK **v2.40.0**, which we will release today or tomorrow.

Thanks again for reporting this!
